name: build-packages
on:
  push:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 69
defaults:
  run:
    shell: bash
jobs:
  #44
  prjtrellis-windows:
    runs-on: "windows-2019"
    env:
      PACKAGE: "bit/prjtrellis"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master
