name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 70
defaults:
  run:
    shell: bash
jobs:

  #7
  icarus-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sim/icarus"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #9
  yosys-linux-py37:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #10
  yosys-linux-py38:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #11
  yosys-plugins-symbiflow-linux:
    runs-on: "ubuntu-20.04"
    needs: ["icarus-linux", "yosys-linux-py37", "yosys-linux-py38", "surelog-linux-py37", "surelog-linux-py38"]
    env:
      PACKAGE: "syn/yosys-plugins-symbiflow"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #15
  symbiflow-yosys-plugins-linux:
    runs-on: "ubuntu-20.04"
    needs: ["icarus-linux", "yosys-linux-py37", "yosys-linux-py38", "surelog-linux-py37", "surelog-linux-py38"]
    env:
      PACKAGE: "syn/symbiflow-yosys-plugins"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #56
  surelog-linux-py37:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/surelog"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #57
  surelog-linux-py38:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/surelog"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #62
  libunwind:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/libunwind"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #63
  gperftools:
    needs: "libunwind"
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/gperftools"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master
