name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 70
defaults:
  run:
    shell: bash
jobs:

  #28
  symbiyosys-linux-py37:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "formal/symbiyosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #29
  symbiyosys-linux-py38:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "formal/symbiyosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master
  #33
  icarus-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sim/icarus"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #34
  verilator-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sim/verilator"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #38
  symbiflow-yosys-plugins-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "syn/symbiflow-yosys-plugins"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #39
  vtr-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "pnr/vtr"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #40
  vtr-gui-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "pnr/vtr-gui"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #48
  nextpnr-ice40-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "pnr/nextpnr/ice40"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #49
  nextpnr-generic-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "pnr/nextpnr/generic"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #51
  tree-sitter-verilog-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/tree-sitter-verilog"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #55
  moore-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/moore"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master
