name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    #    branches: [ master ]
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 70
defaults:
  run:
    shell: bash
jobs:

  #1
  magic-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/magic"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@aj-cbp-bump

  #68
  open_pdks-linux:
    runs-on: "ubuntu-20.04"
    needs: "magic-linux"
    env:
      PACKAGE: "misc/open_pdks"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@aj-cbp-bump
